steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/skillix-dataconnect-bridge:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/skillix-dataconnect-bridge:latest'
      - './dataconnect-bridge'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/skillix-dataconnect-bridge'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'skillix-dataconnect-bridge'
      - '--image'
      - 'gcr.io/$PROJECT_ID/skillix-dataconnect-bridge:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'  # Solo accesible internamente
      - '--set-env-vars'
      - 'NODE_ENV=production,FIREBASE_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'FIREBASE_SERVICE_ACCOUNT=firebase-service-account:latest,API_KEY=dataconnect-api-key:latest'
      - '--service-account'
      - 'skillix-dataconnect@$PROJECT_ID.iam.gserviceaccount.com'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '5'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60'

options:
  logging: CLOUD_LOGGING_ONLY 