import { Response } from 'express';
import { z } from 'zod';
import { LearningPlan, SkillAnalysis, SkillAnalysisSchema } from '../services/llm/schemas';
import * as DataConnectService from '../services/dataConnect.service';
import * as llmService from '../services/llm/learningPlanner.service';
import * as pedagogicalExpert from '../services/llm/pedagogicalExpert.service';
import { UserExperienceLevel, LearningStyle } from '../services/dataConnect.types';
import { AuthenticatedRequest } from '../middleware/auth.middleware';
import * as ContentOrchestrator from '../services/contentOrchestrator.service';

// Esquema de validación para la creación del plan
const CreatePlanInputSchema = z.object({
  onboardingPrefs: z.object({
      skill: z.string(),
      experience: z.enum(['BEGINNER', 'INTERMEDIATE', 'ADVANCED']),
      availableTimeMinutes: z.number().positive(),
      learningStyle: z.enum(['VISUAL', 'AUDITORY', 'KINESTHETIC', 'READING_WRITING', 'MIXED']),
      motivation: z.string(),
      goal: z.string(),
  }),
  skillAnalysis: SkillAnalysisSchema,
});


/**
 * Controlador para crear un nuevo plan de aprendizaje completo.
 */
export const createLearningPlanController = async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { onboardingPrefs, skillAnalysis } = CreatePlanInputSchema.parse(req.body);
    const user = req.user!; // El middleware isAuthenticated garantiza que user exista

    // Guardar las preferencias del usuario
    await DataConnectService.createUserPreference({
      userFirebaseUid: user.firebaseUid,
      user: user,
      skill: onboardingPrefs.skill,
      experienceLevel: onboardingPrefs.experience,
      motivation: onboardingPrefs.motivation,
      availableTimeMinutes: onboardingPrefs.availableTimeMinutes,
      learningStyle: onboardingPrefs.learningStyle,
      goal: onboardingPrefs.goal,
    });
    console.log(`Preferencias guardadas para el usuario ${user.firebaseUid}`);

    // 2. Generar el plan de aprendizaje con el LLM
    console.log(`Generating initial learning plan for skill: "${onboardingPrefs.skill}"...`);
    const initialPlan = await llmService.generateLearningPlanWithOpenAI({
      onboardingData: {
        skill: onboardingPrefs.skill,
        experience: onboardingPrefs.experience,
        time: `${onboardingPrefs.availableTimeMinutes} minutes daily`,
        goal: onboardingPrefs.goal,
        learning_style: onboardingPrefs.learningStyle,
      },
      skillAnalysis: skillAnalysis,
    });

    if (!initialPlan) {
      console.error('Learning plan generation from LLM failed.');
      return res.status(500).json({ message: 'Failed to generate the learning plan.' });
    }
    console.log(`Initial learning plan generated by LLM for: ${onboardingPrefs.skill}`);

    // 3. NEW: Analizar pedagógicamente el plan generado
    console.log(`Analyzing generated plan pedagogically...`);
    const pedagogicalAnalysis = await pedagogicalExpert.analyzePlanPedagogically({
      learningPlan: initialPlan,
      userContext: {
        skill: onboardingPrefs.skill,
        experience: onboardingPrefs.experience,
        time: `${onboardingPrefs.availableTimeMinutes} minutes daily`,
        goal: onboardingPrefs.goal,
        learning_style: onboardingPrefs.learningStyle,
      },
    });

    if (!pedagogicalAnalysis) {
      // No es un error fatal, el plan sigue siendo útil.
      console.warn(`Pedagogical analysis failed for plan on skill "${onboardingPrefs.skill}". Proceeding without it.`);
    } else {
      console.log(`Pedagogical analysis completed for skill: ${onboardingPrefs.skill}`);
    }

    // 4. NEW: Refinar el plan utilizando el análisis pedagógico
    let finalPlan: LearningPlan = initialPlan; // Usar el plan inicial como fallback
    if (pedagogicalAnalysis) {
      console.log('Refining the learning plan using pedagogical analysis...');
      const refinedPlanAttempt = await llmService.generateLearningPlanWithOpenAI({
        onboardingData: {
          skill: onboardingPrefs.skill,
          experience: onboardingPrefs.experience,
          time: `${onboardingPrefs.availableTimeMinutes} minutes daily`,
          goal: onboardingPrefs.goal,
          learning_style: onboardingPrefs.learningStyle,
        },
        skillAnalysis: skillAnalysis,
        pedagogicalAnalysis: pedagogicalAnalysis, // Incluir el análisis para el refinamiento
      });

      if (refinedPlanAttempt) {
        finalPlan = refinedPlanAttempt;
        console.log('Learning plan successfully refined.');
      } else {
        console.warn('LLM plan refinement failed. Proceeding with the initial plan.');
      }
    }

    // Mapear y guardar el plan completo en Data Connect
    const createdPlanResponse = await DataConnectService.createFullLearningPlanInDB(
      user.firebaseUid,
      finalPlan,
      skillAnalysis,
      pedagogicalAnalysis
    );

    const createdPlan = createdPlanResponse?.data?.learningPlan_insert;

    if (!createdPlan || !createdPlan.id) {
        return res.status(500).json({ message: "Failed to save the learning plan to the database." });
    }
    console.log(`Plan de aprendizaje guardado en DB con ID: ${createdPlan.id}`);
    
    // Crear la inscripción (enrollment) para el usuario en este plan
    const enrollment = await DataConnectService.createEnrollment({
      userFirebaseUid: user.firebaseUid,
      learningPlanId: createdPlan.id,
      status: 'ACTIVE',
    });

    if (!enrollment) {
      console.error(`Failed to create enrollment for user ${user.firebaseUid} in plan ${createdPlan.id}.`);
      // No devolvemos un error fatal aquí, pero es una advertencia importante.
    } else {
      console.log(`Enrollment created successfully for user ${user.firebaseUid} in plan ${createdPlan.id}.`);
    }

    // Generar el contenido para el Día 1 usando el orquestador
    console.log(`Triggering content generation for Day 1 of plan ${createdPlan.id}...`);
    const day1Result = await ContentOrchestrator.generateAndSaveContentForDay({
      userId: user.firebaseUid,
      learningPlanId: createdPlan.id,
      dayNumber: 1,
    });

    if (!day1Result.success) {
      // Si la generación del día 1 falla, no hacemos fallar toda la solicitud,
      // pero sí lo registramos como un error crítico. El usuario aún tiene su plan.
      // Se podría reintentar más tarde.
      console.error(`CRITICAL: Learning plan ${createdPlan.id} was created, but content generation for Day 1 failed: ${day1Result.message}`);
    } else {
      console.log(`Content for Day 1 of plan ${createdPlan.id} generated successfully.`);
    }

    // 7. Devolver la respuesta final al cliente
    res.status(201).json({
      message: 'Learning plan created successfully!',
      planId: createdPlan.id,
      skillAnalysis: skillAnalysis,
      pedagogicalAnalysis: pedagogicalAnalysis,
      initialContent: day1Result.success ? day1Result.data : null,
    });

  } catch (error: any) {
    if (error instanceof z.ZodError) {
      return res.status(400).json({ message: 'Invalid input data for plan creation.', errors: error.errors });
    }
    console.error('Error in createLearningPlanController:', error);
    res.status(500).json({ message: 'Internal server error.' });
  }
};
